export const FETCH_TRENDING_GIFS = "FETCH_TRENDING_GIFS";
export const FETCH_SEARCH_GIFS = "FETCH_SEARCH_GIFS";
export const SET_QUERY_PARAM = "SET_QUERY_PARAM";
export const SET_IN_SEARCH = "SET_IN_SEARCH";
export const SET_OFFSET = "SET_OFFSET";
export const SET_PAGES = "SET_PAGES";
